// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7okeuEr0d7jdpmYMpUsQfi6Mnc7EmoAg',
    appId: '1:369230702143:web:05ed6e071370f558d43a8a',
    messagingSenderId: '369230702143',
    projectId: 'belajar-firebase-37c5f',
    authDomain: 'belajar-firebase-37c5f.firebaseapp.com',
    databaseURL:
        'https://belajar-firebase-37c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-firebase-37c5f.appspot.com',
    measurementId: 'G-Z3XEWWEGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwHGcBNbL7FVh7WOs9VFRFKvxrG7Fda8',
    appId: '1:369230702143:android:77910fec3cd9d441d43a8a',
    messagingSenderId: '369230702143',
    projectId: 'belajar-firebase-37c5f',
    databaseURL:
        'https://belajar-firebase-37c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-firebase-37c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQoIigAcQ8kXfa_AS57F5ZleUfcOs-7_U',
    appId: '1:369230702143:ios:10c4ab44efc0471fd43a8a',
    messagingSenderId: '369230702143',
    projectId: 'belajar-firebase-37c5f',
    databaseURL:
        'https://belajar-firebase-37c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-firebase-37c5f.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQoIigAcQ8kXfa_AS57F5ZleUfcOs-7_U',
    appId: '1:369230702143:ios:10c4ab44efc0471fd43a8a',
    messagingSenderId: '369230702143',
    projectId: 'belajar-firebase-37c5f',
    databaseURL:
        'https://belajar-firebase-37c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-firebase-37c5f.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7okeuEr0d7jdpmYMpUsQfi6Mnc7EmoAg',
    appId: '1:369230702143:web:1707b95ef0433920d43a8a',
    messagingSenderId: '369230702143',
    projectId: 'belajar-firebase-37c5f',
    authDomain: 'belajar-firebase-37c5f.firebaseapp.com',
    databaseURL:
        'https://belajar-firebase-37c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-firebase-37c5f.appspot.com',
    measurementId: 'G-HT8F6L1XY0',
  );
}
