// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i15;

import 'package:ditonton/common/state_enum.dart' as _i10;
import 'package:ditonton/domain/entities/episode.dart' as _i12;
import 'package:ditonton/domain/entities/tv_series.dart' as _i11;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_season_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_tv_series_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/remove_watchlist_tv_series.dart'
    as _i6;
import 'package:ditonton/domain/usecases/save_watchlist_tv_series.dart' as _i5;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTVSeriesDetail {
  _FakeGetTVSeriesDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVSeriesRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTVSeriesRecommendations {
  _FakeGetTVSeriesRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVSeriesStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchlistTVSeriesStatus {
  _FakeGetWatchlistTVSeriesStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTVSeries_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistTVSeries {
  _FakeSaveWatchlistTVSeries_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTVSeries_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistTVSeries {
  _FakeRemoveWatchlistTVSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSeasonDetail_5 extends _i1.SmartFake
    implements _i7.GetSeasonDetail {
  _FakeGetSeasonDetail_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVSeriesDetail_6 extends _i1.SmartFake
    implements _i8.TVSeriesDetail {
  _FakeTVSeriesDetail_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailNotifier extends _i1.Mock
    implements _i9.TVSeriesDetailNotifier {
  MockTVSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesDetail),
            returnValue: _FakeGetTVSeriesDetail_0(
              this,
              Invocation.getter(#getTVSeriesDetail),
            ),
          )
          as _i2.GetTVSeriesDetail);

  @override
  _i3.GetTVSeriesRecommendations get getTVSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTVSeriesRecommendations),
            returnValue: _FakeGetTVSeriesRecommendations_1(
              this,
              Invocation.getter(#getTVSeriesRecommendations),
            ),
          )
          as _i3.GetTVSeriesRecommendations);

  @override
  _i4.GetWatchlistTVSeriesStatus get getWatchlistTVSeriesStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTVSeriesStatus),
            returnValue: _FakeGetWatchlistTVSeriesStatus_2(
              this,
              Invocation.getter(#getWatchlistTVSeriesStatus),
            ),
          )
          as _i4.GetWatchlistTVSeriesStatus);

  @override
  _i5.SaveWatchlistTVSeries get saveWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistTVSeries),
            returnValue: _FakeSaveWatchlistTVSeries_3(
              this,
              Invocation.getter(#saveWatchlistTVSeries),
            ),
          )
          as _i5.SaveWatchlistTVSeries);

  @override
  _i6.RemoveWatchlistTVSeries get removeWatchlistTVSeries =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistTVSeries),
            returnValue: _FakeRemoveWatchlistTVSeries_4(
              this,
              Invocation.getter(#removeWatchlistTVSeries),
            ),
          )
          as _i6.RemoveWatchlistTVSeries);

  @override
  _i7.GetSeasonDetail get getSeasonDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getSeasonDetail),
            returnValue: _FakeGetSeasonDetail_5(
              this,
              Invocation.getter(#getSeasonDetail),
            ),
          )
          as _i7.GetSeasonDetail);

  @override
  _i8.TVSeriesDetail get tvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeries),
            returnValue: _FakeTVSeriesDetail_6(
              this,
              Invocation.getter(#tvSeries),
            ),
          )
          as _i8.TVSeriesDetail);

  @override
  _i10.RequestState get tvSeriesState =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesState),
            returnValue: _i10.RequestState.empty,
          )
          as _i10.RequestState);

  @override
  List<_i11.TVSeries> get tvSeriesRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#tvSeriesRecommendations),
            returnValue: <_i11.TVSeries>[],
          )
          as List<_i11.TVSeries>);

  @override
  _i10.RequestState get recommendationState =>
      (super.noSuchMethod(
            Invocation.getter(#recommendationState),
            returnValue: _i10.RequestState.empty,
          )
          as _i10.RequestState);

  @override
  List<_i12.Episode> get seasonEpisodes =>
      (super.noSuchMethod(
            Invocation.getter(#seasonEpisodes),
            returnValue: <_i12.Episode>[],
          )
          as List<_i12.Episode>);

  @override
  _i10.RequestState get episodeState =>
      (super.noSuchMethod(
            Invocation.getter(#episodeState),
            returnValue: _i10.RequestState.empty,
          )
          as _i10.RequestState);

  @override
  int get selectedSeason =>
      (super.noSuchMethod(Invocation.getter(#selectedSeason), returnValue: 0)
          as int);

  @override
  String get message =>
      (super.noSuchMethod(
            Invocation.getter(#message),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#message),
            ),
          )
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#isAddedToWatchlist),
            returnValue: false,
          )
          as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(
            Invocation.getter(#watchlistMessage),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#watchlistMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i14.Future<void> fetchTVSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTVSeriesDetail, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> fetchSeasonEpisodes(int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSeasonEpisodes, [tvId, seasonNumber]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> addWatchlist(_i8.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [tvSeries]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> removeFromWatchlist(_i8.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [tvSeries]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
